name: homework
description: A Social Homework application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: 6.0.0
  # Also update dev/benchmarks/complex_layout/pubspec.yaml
  flutter_gallery_assets: 0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/chuqiao.jpg
    - images/lake.jpg
    - images/TyrionLannister.jpeg
    - packages/flutter_gallery_assets/food/image10.jpg
    - packages/flutter_gallery_assets/food/image11.jpg
    - packages/flutter_gallery_assets/food/image12.jpg
    - packages/flutter_gallery_assets/food/image13.jpg
    - packages/flutter_gallery_assets/food/image1.jpg
    - packages/flutter_gallery_assets/food/image2.jpg
    - packages/flutter_gallery_assets/food/image3.jpg
    - packages/flutter_gallery_assets/food/image4.jpg
    - packages/flutter_gallery_assets/food/image5.jpg
    - packages/flutter_gallery_assets/food/image6.jpg
    - packages/flutter_gallery_assets/food/image7.jpg
    - packages/flutter_gallery_assets/food/image8.jpg
    - packages/flutter_gallery_assets/food/image9.jpg
    - packages/flutter_gallery_assets/food/icons/fish.png
    - packages/flutter_gallery_assets/food/icons/healthy.png
    - packages/flutter_gallery_assets/food/icons/main.png
    - packages/flutter_gallery_assets/food/icons/meat.png
    - packages/flutter_gallery_assets/food/icons/quick.png
    - packages/flutter_gallery_assets/food/icons/spicy.png
    - packages/flutter_gallery_assets/food/icons/veggie.png
    - packages/flutter_gallery_assets/logos/pesto/logo_small.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
